auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: blog.zhengjunwei.com
url: http://blog.zhengjunwei.com
feed: /atom.xml
author_info: <a href="http://blog.zhengjunwei.com">BeiYuu</a>
